---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
  - name: validating-persistentvolumeclaim
    clientConfig:
      service:
        name: webhook-service
        namespace: webhook-system
        path: /validate-v1-persistentvolumeclaim
        port: 8443
    failurePolicy: Fail
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - CREATE
        resources:
          - persistentvolumeclaims
    sideEffects: None
